### ISSUE TITLE
Output GUI does not appear, possibility to save it into output_dir

### ISSUE THREAD

**Issue by JackPieCZ** [berndpfrommer/frequency_cam#10]
When running `ros2 launch frequency_cam frequency_cam.launch.py` in one console and `ros2 bag play ./bag/` in a second console, messages are transferred successfully, but no GUI output is shown.

This issue might be caused by my ignorance of ROS2. Is there another command that is required to run? And is it possible to save the frequency_cam outputs (either generated images or arrays of detected frequencies) to a file/output folder?

Here is the full output of command line 1:
```
DESKTOP:~$ ros2 launch frequency_cam frequency_cam.launch.py
[INFO] [launch]: All log files can be found below ...
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [frequency_cam_node-1]: process started with pid [685]
[frequency_cam_node-1] [INFO] [1717088718.397301981] [frequency_cam]: publishing frequency: 25
[frequency_cam_node-1] [INFO] [1717088718.420007083] [frequency_cam]: frequency range: 10 -> 5000
[frequency_cam_node-1] [INFO] [1717088718.424259784] [frequency_cam]: node started up!
[frequency_cam_node-1] [INFO] [1717088720.420387187] [frequency_cam]: no events received
[frequency_cam_node-1] [INFO] [1717088722.420405992] [frequency_cam]: no events received
[frequency_cam_node-1] [INFO] [1717088724.420366496] [frequency_cam]: no events received
[frequency_cam_node-1] [INFO] [1717088726.420364303] [frequency_cam]:  25.80 Mev/s,   787.68 msgs/s,    38.77 nsec/ev    1270 usec/msg, drop:  15
[frequency_cam_node-1] [INFO] [1717088728.420485218] [frequency_cam]: no events received
```

Here is the full output of command line 2:
```
DESKTOP:~$ ros2 bag play ./bag
[INFO] [1717088724.670850721] [rosbag2_player]: Set rate to 1
[INFO] [1717088724.692886224] [rosbag2_player]: Adding keyboard callbacks.
[INFO] [1717088724.692952924] [rosbag2_player]: Press SPACE for Pause/Resume
[INFO] [1717088724.693003724] [rosbag2_player]: Press CURSOR_RIGHT for Play Next Message
[INFO] [1717088724.693052124] [rosbag2_player]: Press CURSOR_UP for Increase Rate 10%
[INFO] [1717088724.693064624] [rosbag2_player]: Press CURSOR_DOWN for Decrease Rate 10%
[INFO] [1717088724.693181924] [rosbag2_player]: Playback until timestamp: -1
kolarj55@DESKTOP-12QSBK1:~$
```

**Comment by berndpfrommer** [comment]
There is no GUI :)

The way it works in ROS is this: the frequency_cam node publishes an image, and you can subscribe to that topic and view it with a viewer like:
``` 
ros2 run rqt_image_view rqt_image_view
```
(or ``rqt_gui rqt_gui``)

You may first want to run an ``event_camera_renderer`` (make sure the topics match!) and then subscribe to that image to see that your events look good.

**Comment by JackPieCZ** [comment]
Oh, okay! :) Thank you very much!

**Comment by berndpfrommer** [comment]
Unfortunately, unless you want to write a custom ROS2 node,  there is no direct way to save the images into individual frames.
The way to do it then is to record the images published by frequency_cam  into a rosbag (ros2 bag record ...) and then extract the individual frames with something like this:

https://github.com/MapIV/ros2_bag_to_image

**Comment by JackPieCZ** [comment]
One last thing, is it possible to pass different debug pixels into the FrequencyCam class?
I would imagine it would look similar to `ros2 launch frequency_cam frequency_cam.launch.py debug_pixels:=(240,194)`.

**Comment by berndpfrommer** [comment]
I don't recall, sorry, you'll have to look at the code just like me.
