### ISSUE TITLE
Running on DAVIS data

### ISSUE THREAD

**Issue by ghoshsuman** [berndpfrommer/frequency_cam#3]
Hi. I would like to run the frequency_cam code on some data I recorded using DAVIS346. I have ROSBags with `dvs_msgs::EventArray` type messages like [this](https://github.com/uzh-rpg/rpg_dvs_ros/tree/master/dvs_msgs).
As you suggested in the README, I tried running the `event_array_tools` `republish` node as follows: 
    
    roslaunch event_array_tools republish_node.launch camera:=dvs message_type:=dvs

 but I think this converts `event_array_msgs/EventArray` to `dvs_msgs/EventArray`. I need the converse of this. 
How can I do this?

**Comment by berndpfrommer** [comment]
I'm afraid that is currently not possible. Let me see what it would take to implement a conversion tool. I should have an answer (or an implementation) for you by tonight.

**Comment by berndpfrommer** [comment]
The legacy_to_bag tool in the event_array_tools repo should allow you to convert the bag. Here is the corresponding PR:
https://github.com/berndpfrommer/event_array_tools/pull/4
It has been merged into the master. Simply pulling the master should suffice to get the tool (usage in README).

**Comment by ghoshsuman** [comment]
Thanks for this tool. Unfortunately, I am getting segmentation fault when I run it. I think it's failing [here](https://github.com/berndpfrommer/event_array_tools/blob/1b14e65359333daa990e3bd2f9c47b74aba9ae39/src/legacy_to_bag_ros1.cpp#L47). Any idea what might be causing it?

**Comment by berndpfrommer** [comment]
Have you also pulled the event_array_codecs repo before rebuilding the
updated event_array_tools?

**Comment by ghoshsuman** [comment]
Thanks! That worked.
